name: wheels

on:
  push:
    branches: [windows-wheels]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: ubuntu-latest
          #   py: "cp39*"
          - os: windows-latest
            py: "cp39*"
          # - os: macos-latest
          #   name: macos-x86_64
          #   macos_arch: "x86_64"
          #   py: "cp39*"
          # - os: macos-latest
          #   name: macos-arm64
          #   macos_arch: "arm64"
          #   py: "cp39*"

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: aarch64

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60
        with:
          limit-access-to-actor: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_CONFIG_SETTINGS_WINDOWS: cmake.args="-GNinja"


      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
